#!/bin/bash
#Install Tor for Raspberry Pi and configure IP tables
#Must be ran as ROOT 

/bin/echo "Updating system and installing dhcp and Tor:"
#/usr/bin/apt-get -y update
#/usr/bin/apt-get -y upgrade
apt-get install -y dnsmasq
/usr/bin/apt-get -y install tor 

/bin/echo "Firewall settings:"
/sbin/iptables -t nat -A PREROUTING -i eth1 -p tcp --dport 22 -j REDIRECT --to-ports 22
/sbin/iptables -t nat -A PREROUTING -i eth1 -p udp --dport 53 -j REDIRECT --to-ports 53
/sbin/iptables -t nat -A PREROUTING -i eth1 -p tcp --syn -j REDIRECT --to-ports 9040
/sbin/iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
/sbin/iptables -A FORWARD -i eth0 -o eth1 -m state --state RELATED,ESTABLISHED -j ACCEPT
/sbin/iptables -A FORWARD -i eth1 -o eth0 -j ACCEPT

/bin/sh -c "/sbin/iptables-save > /etc/iptables.ipv4.nat"

/bin/echo "Creating Log:"
/usr/bin/touch /var/log/tor/notices.log
/bin/chown debian-tor /var/log/tor/notices.log
/bin/chmod 644 /var/log/tor/notices.log



/bin/echo "Configuring eth1:"
/bin/cat >> /etc/network/interfaces <<eth_config 
## ETH1 static ip
iface eth1 inet static
address 192.168.0.1
netmask 255.255.255.0

eth_config


/bin/echo "Configuring dhcp:"
/bin/cat >> /etc/dnsmasq.conf <<dnsmasq_config 
interface=eth1
dhcp-range=eth1,192.168.0.10,192.168.0.200,2h
dhcp-option=3,192.168.0.1 # our router
dhcp-option=6,192.168.0.1 # our DNS Server
dhcp-authoritative # force clients to grab a new IP

dnsmasq_config




/bin/echo "Configuring Tor access from eth1:"
/bin/cat >/etc/tor/torrc <<tor_config 
## ETH1 is workstation access
## Assumes you've configured your access point similar to LadyAda's "Pi as Access Point" tutorial

# Log File
Log notice file /var/log/tor/notices.log

VirtualAddrNetwork 10.192.0.0/10
AutomapHostsSuffixes .onion,.exit
AutomapHostsOnResolve 1

# Transparent Port
TransPort 9040
TransListenAddress 192.168.0.1

# DNS Port
DNSPort 53
DNSListenAddress 192.168.0.1

## Tor Relay Configuration

# SOCKS Port
SocksPort 0

# Run Tor as Daemon (0 for no, 1 for yes)
RunAsDaemon 1

# Run Tor only as a client, not as a relay
ClientOnly
tor_config

/bin/echo "Ensuring Tor starts when system boots up:"
/usr/sbin/update-rc.d tor enable

/bin/echo "Starting the Tor service:"
/usr/sbin/service tor start

/usr/bin/clear
/bin/echo "Done!"

exit
